# Generated by Django 3.2 on 2024-02-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text_owner',
            new_name='author',
        ),
    ]
